# Generated by Django 4.2.3 on 2023-07-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0002_alter_deposite_amount_alter_profile_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbaord.profile')),
            ],
        ),
    ]
